import { useEffect, useMemo, useState } from "react";
import { mapApi, surveysApi } from "../../api/services";
import type { SubmissionMapPoint, SurveySummary } from "../../api/types";
function clamp(n:number,min:number,max:number){return Math.max(min,Math.min(max,n));}
export function MapPage(){
 const [surveys,setSurveys]=useState<SurveySummary[]>([]),[surveyId,setSurveyId]=useState(""),[points,setPoints]=useState<SubmissionMapPoint[]>([]),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{setPoints(await mapApi.submissionPoints(surveyId?{survey_id:surveyId}:undefined));}finally{setLoading(false);}}
 useEffect(()=>{surveysApi.list().then(x=>{setSurveys(x);}).catch(()=>{});},[]); useEffect(()=>{load();},[surveyId]);
 const bounds=useMemo(()=>{if(!points.length)return null;const la=points.map(p=>p.latitude),lo=points.map(p=>p.longitude);return{minLat:Math.min(...la),maxLat:Math.max(...la),minLon:Math.min(...lo),maxLon:Math.max(...lo)}},[points]);
 const pos=(p:SubmissionMapPoint)=>{if(!bounds)return{left:"50%",top:"50%"};const xs=Math.max(bounds.maxLon-bounds.minLon,.001),ys=Math.max(bounds.maxLat-bounds.minLat,.001);return{left:`${clamp(8+(p.longitude-bounds.minLon)/xs*84,5,95)}%`,top:`${clamp(8+(1-(p.latitude-bounds.minLat)/ys)*84,5,95)}%`};};
 return <div><div className="page-header"><div><h1>Submission Map</h1><p>Explore GPS-tagged field submissions geographically.</p></div><button onClick={load}>Refresh</button></div><div className="toolbar"><select value={surveyId} onChange={e=>setSurveyId(e.target.value)}><option value="">All surveys</option>{surveys.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select><span>{points.length} GPS point{points.length===1?"":"s"}</span></div>{loading?<p className="loading-text">Loading map data…</p>:!points.length?<div className="empty-state"><h3>No GPS submissions</h3><p>Submissions with captured latitude and longitude will appear here.</p></div>:<><div style={{display:"grid",gridTemplateColumns:"minmax(0,2fr) minmax(280px,1fr)",gap:20}}><div style={{position:"relative",height:520,borderRadius:14,overflow:"hidden",border:"1px solid #d9e0d8",background:"linear-gradient(145deg,#edf3ea,#dfe9f0)"}}><div style={{position:"absolute",inset:0,backgroundImage:"linear-gradient(rgba(60,80,60,.08) 1px,transparent 1px),linear-gradient(90deg,rgba(60,80,60,.08) 1px,transparent 1px)",backgroundSize:"40px 40px"}}/><div style={{position:"absolute",left:16,top:12,fontSize:12,background:"rgba(255,255,255,.88)",padding:"6px 9px",borderRadius:8}}>GPS submission map • relative extent</div>{points.map(p=><button key={p.id} title={`${p.survey_title} • ${p.latitude.toFixed(5)}, ${p.longitude.toFixed(5)}`} onClick={()=>window.open(`https://www.openstreetmap.org/?mlat=${p.latitude}&mlon=${p.longitude}#map=15/${p.latitude}/${p.longitude}`,"_blank","noopener,noreferrer")} style={{position:"absolute",...pos(p),transform:"translate(-50%,-50%)",width:18,height:18,borderRadius:"50%",border:"3px solid white",background:"#c94b3b",boxShadow:"0 2px 8px rgba(0,0,0,.3)",cursor:"pointer"}}/>)}</div><div className="table-wrap" style={{maxHeight:520,overflow:"auto"}}><table><thead><tr><th>Survey</th><th>Coordinates</th><th>Open</th></tr></thead><tbody>{points.map(p=><tr key={p.id}><td>{p.survey_title}</td><td>{p.latitude.toFixed(5)}, {p.longitude.toFixed(5)}</td><td><a href={`https://www.openstreetmap.org/?mlat=${p.latitude}&mlon=${p.longitude}#map=15/${p.latitude}/${p.longitude}`} target="_blank" rel="noreferrer">Map</a></td></tr>)}</tbody></table></div></div><p style={{fontSize:12,opacity:.7,marginTop:12}}>The overview uses a dependency-free geographic plot. Selecting a point opens OpenStreetMap at the exact coordinates.</p></>}</div>;
}
